//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGame.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1671452990561_2c788a350c09a11b6607c016d5c9f5b0 {
            get {
                object obj = ResourceManager.GetObject("1671452990561_2c788a350c09a11b6607c016d5c9f5b0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1671452990561_2c788a350c09a11b6607c016d5c9f5b01 {
            get {
                object obj = ResourceManager.GetObject("1671452990561_2c788a350c09a11b6607c016d5c9f5b01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ground {
            get {
                object obj = ResourceManager.GetObject("ground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_flappy_bird_floppy_garuda_clip_art_android_5b750dc44f65b4_8782030215343978923252 {
            get {
                object obj = ResourceManager.GetObject("kisspng-flappy-bird-floppy-garuda-clip-art-android-5b750dc44f65b4.878203021534397" +
                        "8923252", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_flappy_bird_floppy_garuda_clip_art_android_5b750dc44f65b4_8782030215343978923252_transformed {
            get {
                object obj = ResourceManager.GetObject("kisspng-flappy-bird-floppy-garuda-clip-art-android-5b750dc44f65b4.878203021534397" +
                        "8923252-transformed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_flappy_bird_floppy_garuda_clip_art_android_5b750dc44f65b41 {
            get {
                object obj = ResourceManager.GetObject("kisspng-flappy-bird-floppy-garuda-clip-art-android-5b750dc44f65b41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_super_mario_brothers_computer_game_warp_tunnel_tube_sprite_green_computer_green_laptop_green_gaming_green_game {
            get {
                object obj = ResourceManager.GetObject("png-transparent-super-mario-brothers-computer-game-warp-tunnel-tube-sprite-green-" +
                        "computer-green-laptop-green-gaming-green-game", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_super_mario_brothers_computer_game_warp_tunnel_tube_sprite_green_computer_green_laptop_green_gaming_green_game__1_ {
            get {
                object obj = ResourceManager.GetObject("png-transparent-super-mario-brothers-computer-game-warp-tunnel-tube-sprite-green-" +
                        "computer-green-laptop-green-gaming-green-game (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_super_mario_brothers_computer_game_warp_tunnel_tube_sprite_green_computer_green_laptop_green_gaming_green_game__2_ {
            get {
                object obj = ResourceManager.GetObject("png-transparent-super-mario-brothers-computer-game-warp-tunnel-tube-sprite-green-" +
                        "computer-green-laptop-green-gaming-green-game (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Птичка {
            get {
                object obj = ResourceManager.GetObject("Птичка", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Птичка__1_ {
            get {
                object obj = ResourceManager.GetObject("Птичка (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Птичка__1___1_ {
            get {
                object obj = ResourceManager.GetObject("Птичка (1) (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Труба_сверху__1_ {
            get {
                object obj = ResourceManager.GetObject("Труба сверху (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Труба_снизу_transformed {
            get {
                object obj = ResourceManager.GetObject("Труба_снизу-transformed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Трубы_Flappy_Bird {
            get {
                object obj = ResourceManager.GetObject("Трубы Flappy Bird", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Трубы_Flappy_Bird1 {
            get {
                object obj = ResourceManager.GetObject("Трубы Flappy Bird1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
